In [3]:
import numpy as np
import math

matrix = np.arange(15).reshape(3, 5)
print(matrix)
# Important
matrix = np.atleast_2d(matrix)
# set maximum to -inf
maximum = -math.inf
# Search maximum
for j in range(matrix.shape[1]):
    for i in range(matrix.shape[0]):
        maximum = matrix[i][j] if matrix[i][j] > maximum else maximum

# More than 1 maximum, take the first one?
pos = np.argwhere(matrix == maximum)[0]
print(
    f"The maximum value of the array is: {maximum}, located at: row {pos[0]}, column {pos[1]}"
)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
The maximum value of the array is: 14, located at: row 2, column 4
